# Generated by Django 6.0 on 2025-12-22 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitedesp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='despp',
        ),
    ]
