# Generated by Django 6.0 on 2025-12-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sitedesp', '0002_delete_despp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=25)),
            ],
        ),
    ]
