# Generated by Django 6.0 on 2026-02-12 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitedesp', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despp',
            old_name='firstname',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='despp',
            old_name='lastname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='despp',
            name='phone',
        ),
    ]
